org: jaimealexdev
app: tj-marketplace
service: products-function

stages:
  default:
    params:
      tableName: "tj-market-products"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:us-east-1:846928055763:table/tj-market-products
        - Effect: Allow
          Action: 
            - dynamodb:Query
          Resource: 
            - arn:aws:dynamodb:us-east-1:846928055763:table/tj-market-products
            - arn:aws:dynamodb:us-east-1:846928055763:table/tj-market-products/index/title-index
  environment:
    USERS_TABLE: "tj-market-products"

functions:
  api:
    handler: products-handler.handler
    events:
      - httpApi:
          path: "*"
          method: "*"
          cors:
            allowedOrigins:
              - "*"
            allowedHeaders:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowedMethods:
              - GET
              - POST
              - OPTIONS

# Configure HTTP API CORS at the API Gateway level
resources:
  Resources:
    HttpApiCors:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: HttpApi
        ProtocolType: HTTP
        CorsConfiguration:
          AllowOrigins:
            - '*'
          AllowHeaders:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
          AllowMethods:
            - GET
            - POST
            - OPTIONS
